### ISSUE TITLE
Unclear error message when CAS is set to "Refuse Access"

### ISSUE THREAD

**Issue by jcguan1** [pressbooks/pressbooks-cas-sso#12]
### Description

Current error message when user logs in successfully via CAS but does not exist in Pressbooks AND CAS is configured to Refuse Access to new users is: "CAS authentication failed", which suggests the login info is wrong or some other server issue. 

This message should be changed to: 

> Unable to log in: You do not have an account on this Pressbooks network. 
> To request an account, please contact your institution's Pressbooks Network Manager: $network_manager_contact. 

 

Where $network_manager_contact is a string. Input is from a text box (that needs to be created) in the Network Settings that would let Network Managers specify name and email of a contact at their institution.

### Steps to Reproduce

1. Make sure your CAS user doesn't exist in Pb
2. Set CAS setting to "Refuse Access" to new users
3. Log in via CAS with user credentials

**Expected behavior:** 
Sensible error message

**Actual behavior:** 
"CAS authentication failed"

**Comment by jcguan1** [comment]
Text box in Network Settings to specify main network manager contact for users. 
![image](https://user-images.githubusercontent.com/37554869/40721921-e1d1715e-63e8-11e8-87de-0ad279c304da.png)

**Comment by dac514** [comment]
@jcguan1 Looks like there's no hook (action, filter) that allows me to inject a form element into Network Settings at that position. I can only put it at the bottom of the form right before the submit button. Also, If I do that, I will have to write extra code to handle the submission which I don't think is a good idea.

I'm going to put in the CAS Admin menu instead. Hope that's OK?

**Comment by jcguan1** [comment]
Hmm... Actually, can you pull the email from the Aldine contact form instead? Since it's a field I'd like to reuse in a more general context (and not all users will have CAS), I'd rather avoid multiplying fields.

If field is empty, error message should just say:
> Unable to log in: You do not have an account on this Pressbooks network.
> To request an account, please contact your institution's Pressbooks Network Manager.


![image](https://user-images.githubusercontent.com/37554869/40734279-f426cae4-6405-11e8-8d2e-b3f3c741690d.png)
