### ISSUE TITLE
Button on login page does not handle long text strings well

### ISSUE THREAD

**Issue by jcguan1** [pressbooks/pressbooks-cas-sso#7]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-cas-sso/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-cas-sso) to see if your bug or enhancement is already listed?

### Description

The "Connect via CAS" button on the Pressbooks login form has fixed size, so if we personalize the text with a string that is too long, it will just run off the button. 

### Steps to Reproduce

1. Enable CAS
2. In the settings, set button text to a long string (ex: "Log in via your university NetID")
3. visit login page. 

**Expected behavior:** 
Text wrapping or button resize.
Note: I don't expect this button to handle arbitrary string lengths, but maybe 2 lines of text would be reasonable?

**Actual behavior:** 
Text on one line and runs beyond the button.

**Comment by greatislander** [comment]
Fixed in pressbooks/pressbooks@283e570. You can add a `<br>` tag in the field on the options page to break the button text into two lines.
