### ISSUE TITLE
Login form UX

### ISSUE THREAD

**Issue by jcguan1** [pressbooks/pressbooks-cas-sso#8]
### Description

Order of elements in the login form is a bit confusing when SSO is enabled: 

1. Given that most networks with SSO will want their users to login via SSO, the "Connect via CAS" button should be above the Pressbooks login form fields. 
2. This will also ensure that the "Lost your Password?" link (which links to the PB password reset) is grouped with the local PB login form elements. 

### Steps to Reproduce

1. Enable CAS
2. Look at Login page

**Expected behavior:** 
![expected login form](https://user-images.githubusercontent.com/37554869/40239410-f445a63e-5a83-11e8-9757-6ade283ab103.png)

**Actual behavior:** 

![current login form](https://user-images.githubusercontent.com/37554869/40239438-0a3145e8-5a84-11e8-93b8-7f15c7737a48.png)

**Comment by dac514** [comment]
The button was moved there to be compatible with https://wordpress.org/plugins/shibboleth/

Given that the shibboleth plugin has 1,000+ active installations, and given that we will not be able to move the Shibboleth button if we decide use that plugin, I'm more inclined to go with the flow?

**Comment by dac514** [comment]
37 million users confused?

![image](https://user-images.githubusercontent.com/812192/40240647-080158be-5a87-11e8-8ad1-9594e352549d.png)

**Comment by jcguan1** [comment]
The bigger problem is the "lost your password" link, which ends up showing under the "Connect via CAS" button.

**Comment by dac514** [comment]
Strong opinions about UX vs. existing conventions about UX vs. data about UX lead to fun discussions. :)

**Comment by dac514** [comment]
There are definitely improvements that could be made. The Google branding for the button on WordPress dot com makes it much less confusing, for example.

I just wanted to caution about the position of the button, and explain why it was put there.

As Pressbooks developers we inherit WordPresss conventions. Breaking them makes things more difficult for us when maintaining the software long term.

**Comment by greatislander** [comment]
Closing this for now; it can be revisited in future if desired.
